### Data Analysis 
- The study of data is called data science
- analysing the data
- *data is the meaningful information*
- **Data is of many types  **
    1. Data in the devices
        - .txt,.doc,.xls,.apk,.mp4,.mp3,.exe etc
    2. Data in the real world
        - 2 types  
            1. Quantitative and 
                - data is about size/volume
                - 2types:1.Discrete and 2.Continuous
                    - discrete data is fixed/constant
                        - numbers on the die:varies from 1 to 6
                        - color,nationality etc
                    - Data is continuous
                        - time,weight,height,
            2. Qualitative
                - Data is catogorized based on the quality
                    - data submission in feedback form/review of product purchased online 
                        - Good,avaerage,excellent,extreamly good
  
   
  3. Data in Statistics
       - Nominal,Ordinal and Rational
        - Data is catogorized on the basis of name
            - COLOR,nationality, 
        - Ordinal:it depends upon the order of data
            - feedback form
        - Rational: data is in the form of ratio(division),addition,subtraction,multiplication etc

#### Stages of Data Science
- Data existance
- Data gathering
- Data representation
- Data analysis

#### Data Gathering
- collection of data is possible through importing modules

#### Modules
1. numpy
    - to collect the data,to work with array type,scientific computation
2. Pandas
    - work analysis,manipulation and cleaning of data
3. Matlplotlib & seaborn
    - data visualization module
4. Scikit Learn(sklean)
    - data preprocessing,importing datasets,to build the models

#### Numpy
- Numpy stands for NumericalPython
- is used to deal with array type of data
- mainly used for scientific computation
- **working procedure**
    - install the numpy in your local machine
        - pip install numpy
    - import the module at our workspace
        - import numpy

In [1]:
import numpy 

In [2]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [3]:
import numpy as n

In [4]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [6]:
with open("data.txt") as f:
    print(f.read())

 I am Ruthu from APSSDC 
 Working as Machine Learning Traienr
 at present conducted ML Workshop for Aditya college students


In [7]:
type(f)

_io.TextIOWrapper

In [8]:
n.__version__

'1.16.5'

#### Working with Numpy
- arrays()
    - homogenous data structure
    - immutable

#### Creation of arrays
- array() is the sub module of numpy

In [9]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [12]:
st=n.array("Start with strings")
st # cratiing the array using str

array('Start with strings', dtype='<U18')

In [11]:
print(st)

Start with strings


In [14]:
# creating array using list/tuple
t=n.array((6,7,4,3,"hi"))
t

array(['6', '7', '4', '3', 'hi'], dtype='<U11')

In [15]:
print(t)

['6' '7' '4' '3' 'hi']


In [18]:
li=n.array([5,6,9,2,1,4])
print(li)

[5 6 9 2 1 4]


In [20]:
# creating arrays using dict
s={9,5,6,'hi',8,9,5,8,'hello'}
print(n.array(s))

{5, 6, 8, 9, 'hi', 'hello'}


In [21]:
s

{5, 6, 8, 9, 'hello', 'hi'}

In [22]:
sa=n.array(s)
sa

array({5, 6, 8, 9, 'hi', 'hello'}, dtype=object)

In [23]:
type(sa)

numpy.ndarray

In [26]:
dic={9:3,8:3,'hi':'hello'}
nd=n.array(dic)
print(nd)

{9: 3, 8: 3, 'hi': 'hello'}


In [27]:
type(nd)

numpy.ndarray

In [33]:
# creating arrays using range()
rn=n.array(range(10))
print(rn)
lw,up=int(input()),int(input())
rn2=n.array(range(lw,up))
print(rn2)
rn3=n.array(range(lw,up,6))
print(rn3)

[0 1 2 3 4 5 6 7 8 9]
10
50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 16 22 28 34 40 46]


In [34]:
mp=list(map(int,input().split()))
print(n.array(mp))

90 87 56 4 3 2 10 89
[90 87 56  4  3  2 10 89]


In [35]:
# we can also create n-dimensional arrays
# we can create arrays with of dimensions 32

In [39]:
lt=n.array([[3],[5],[6],[9]])
print(lt) # column matrix

[[3]
 [5]
 [6]
 [9]]


In [40]:
# 2d arrays
d2=n.array([(6,7,9),(9,4,5)])
d2

array([[6, 7, 9],
       [9, 4, 5]])

In [41]:
d2.dtype # datatype of each element

dtype('int32')

In [42]:
d2.itemsize # int:4bytes

4

In [43]:
d2.shape # rows,col

(2, 3)

In [44]:
d2.size # no.of elements

6

In [47]:
# creating multi dimensional arrays
#3d array:no.of arrays,row,col
d3=n.array([6,7,8,12,34,90],ndmin=4) # to assign the dimensions
d3

array([[[[ 6,  7,  8, 12, 34, 90]]]])

In [48]:
d2.ndim #to check the dimensions of existed array

2

In [53]:
n.array((8,5,6,12,'hi'),ndmin=32)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[['8',
                                      '5',
                                      '6',
                                      '12',
                                      'hi']]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]],
      dtype='<U11')

In [56]:
mul=n.array([[[3,4,5],[7,8,9]],[[10,12,34],[90,78,45]]])
print(mul )# 2 sub arrays which is of 2d 

[[[ 3  4  5]
  [ 7  8  9]]

 [[10 12 34]
  [90 78 45]]]


In [55]:
mul[0]

array([[3, 4, 5],
       [7, 8, 9]])

In [62]:
m=n.array([[[4,5],[9,4],[8,2],[1,2],[8,4]]])
print(m)
m.ndim

[[[4 5]
  [9 4]
  [8 2]
  [1 2]
  [8 4]]]


3

In [63]:
m[0]

array([[4, 5],
       [9, 4],
       [8, 2],
       [1, 2],
       [8, 4]])

In [64]:
mul[0]

array([[3, 4, 5],
       [7, 8, 9]])

In [65]:
mul[1]

array([[10, 12, 34],
       [90, 78, 45]])

#### Creating arrays without array()
1. ones()
2. full()
3. fill()
4. zeros()
5. eye()
6. diag()
7. arange()
8. linspace()
9. random()

In [68]:
o=n.ones(4)
o # row matrix

array([1., 1., 1., 1.])

In [70]:
o2=n.ones((4,5)) # (row,col)
o2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
# entire array filled with only zeros
z=n.zeros(6)
print(z)
z2=n.zeros((5,3),dtype=int)
z2

[0. 0. 0. 0. 0. 0.]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [76]:
i=n.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
i2=n.eye(3,dtype=int)
i2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**full() and fill()**

In [82]:
fl=n.full(5,6) # (row,ele)
fl # row col

array([6, 6, 6, 6, 6])

In [84]:
fl2=n.full((3,4),input())
fl2 # 2d array

I am ruthu


array([['I am ruthu', 'I am ruthu', 'I am ruthu', 'I am ruthu'],
       ['I am ruthu', 'I am ruthu', 'I am ruthu', 'I am ruthu'],
       ['I am ruthu', 'I am ruthu', 'I am ruthu', 'I am ruthu']],
      dtype='<U10')

In [87]:
fl2.fill('new') # replace old with new
fl2

array([['new', 'new', 'new', 'new'],
       ['new', 'new', 'new', 'new'],
       ['new', 'new', 'new', 'new']], dtype='<U10')

In [90]:
fl2.fill(1)
fl2

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U10')

In [91]:
# diagonal matrix
# you can print the diagonal elements

In [98]:
dg=n.diag(d2)
dg

array([6, 4])

In [95]:
d2

array([[6, 7, 9],
       [9, 4, 5]])

In [99]:
d=n.diag([6,7,8,9])
d

array([[6, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [100]:
# arange()
ar=n.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [101]:
ar2=n.arange(10,45)
ar2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])

In [102]:
ar3=n.arange(10,56,7)
ar3

array([10, 17, 24, 31, 38, 45, 52])

In [103]:
len(ar3)

7

In [104]:
len(ar2) # 35:1x35,7x5,5x7,35x1

35

In [105]:
ar2.reshape(7,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [107]:
# represent unknow values with -ve index
ar2.reshape(5,-3)

array([[10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44]])

In [108]:
ar2.reshape(5,-1)

array([[10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44]])

In [109]:
ar2.reshape(-1,7)

array([[10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43, 44]])

In [110]:
ar2.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [113]:
# using reshape you can create multi dimensional arrays
m3=n.arange(45).reshape(3,5,3)
print(m3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]


In [115]:
m4=n.arange(45).reshape(5,3,3)
m4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [116]:
m4[3]

array([[27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

#### random()
- random() is the sub module of numpy
- is used to generate random values in a given
- random.rand()
- random.random()
- random.randint()
- random.randn()

In [123]:
r=n.random.randint(45) # 0 to 45
r

25

In [136]:
r=n.random.randint(100,450,30)
r

array([389, 187, 334, 346, 446, 302, 171, 361, 246, 252, 287, 216, 224,
       244, 378, 414, 170, 425, 133, 127, 268, 192, 273, 420, 266, 401,
       233, 246, 199, 238])

In [132]:
n.random.randint(int(input()),int(input()),int(input()))

90
400
123


array([199, 352, 237, 125, 364, 375, 393, 396, 219, 394, 243, 113, 137,
       148, 141, 126, 369, 208, 165, 360, 297, 336, 265, 389, 364, 190,
       127, 104, 347, 335, 365, 313, 180, 364,  96, 231, 174, 278, 150,
       258, 101, 178,  91, 212, 337, 143, 185, 215, 117, 381, 353, 133,
       309, 140, 280, 396, 323, 362, 106, 158, 176, 113,  92, 270, 237,
       113, 382, 216, 215, 289, 288, 177, 172, 119, 133, 195, 351, 309,
       110, 114, 247, 335, 374, 127,  97, 182, 373, 388, 301, 299,  99,
       104, 232, 202, 354, 135, 307, 384, 187, 304, 262, 140, 214, 272,
       236, 340, 131, 308, 328, 176, 379, 216, 271, 353, 191, 355,  90,
       201, 153,  93,  93, 206, 377])

In [137]:
# linspace:linear space:diving the given range of data into equal parts

In [139]:
ln=n.linspace(10,45) # by default 50 samples
ln

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ,
       20.71428571, 21.42857143, 22.14285714, 22.85714286, 23.57142857,
       24.28571429, 25.        , 25.71428571, 26.42857143, 27.14285714,
       27.85714286, 28.57142857, 29.28571429, 30.        , 30.71428571,
       31.42857143, 32.14285714, 32.85714286, 33.57142857, 34.28571429,
       35.        , 35.71428571, 36.42857143, 37.14285714, 37.85714286,
       38.57142857, 39.28571429, 40.        , 40.71428571, 41.42857143,
       42.14285714, 42.85714286, 43.57142857, 44.28571429, 45.        ])

35 values are splitted into 50 samples by default

In [140]:
ln2=n.linspace(10,60,7)  # both limits are inclusive
ln2

array([10.        , 18.33333333, 26.66666667, 35.        , 43.33333333,
       51.66666667, 60.        ])

In [142]:
51/7

7.285714285714286

In [143]:
np=range(1,10)
len(np)

9

In [147]:
lnp=n.linspace(1,10)
len(lnp)

50

1,2,3,4,5,6,7,8,9,10: 1 to 9

In [153]:
n.random.random((3,4))
# it will arrange random samples of size from 0 to 1

array([[0.56489382, 0.93482789, 0.02750151, 0.85289682],
       [0.16180428, 0.83932357, 0.54275888, 0.82826093],
       [0.48307628, 0.70877593, 0.06638389, 0.95778909]])

In [157]:
n.random.rand(4,5) # from 0 to 1

array([[0.69539306, 0.12140524, 0.08261373, 0.19695833, 0.98295014],
       [0.17477102, 0.39786446, 0.71597714, 0.11429569, 0.13356376],
       [0.08593503, 0.67079746, 0.52505258, 0.73744159, 0.00216646],
       [0.42640867, 0.53695982, 0.54822051, 0.05756075, 0.371551  ]])

In [168]:
var=n.random.randn(4,7)
var

array([[-1.0501494 ,  0.02152062, -0.27864357,  1.29584266, -0.85366517,
         0.28763451, -0.09072633],
       [ 0.18572452,  0.89972198,  0.38582977, -0.88145077,  1.2003528 ,
        -0.5994615 , -1.07163772],
       [-1.2961856 ,  0.33353433, -0.02839401,  0.64389843,  0.21081263,
        -0.10101327,  0.72585847],
       [ 0.82005168, -0.26242181, -1.01486348,  0.16046085, -1.24289593,
         2.46057809,  0.63953935]])

In [162]:
n.max(var)

2.3090034384211555

In [163]:
n.min(var)

-1.911829531127555

In [164]:
n.sum(var)

-3.420798771980853

#### Accessing the data elements in array
- using index
    - 2types:
        1. formal/+ve and -ve
            1. +ve starts from to goes upto +infinite
            2. -ve starts from -1 and upto -infinite
        2. fancy indexing
            - condition based

In [175]:
# create the array of size 5x5 randomly

In [180]:
r5=n.random.randint(60,200,25).reshape(5,-1)
r5

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [181]:
r5[0] # it gives the first row of elements

array([100, 117, 192, 198, 110])

In [182]:
r5[4]

array([106, 118, 142, 161, 190])

In [185]:
r5[-1] # last row

array([106, 118, 142, 161, 190])

In [186]:
r5[-2] # last but one row

array([162, 101, 120, 157, 123])

In [188]:
r5[2] # third row

array([166,  80,  97, 162,  77])

In [190]:
# slicing:extracting sub array of elements using index
# [start:stop:step_count]

In [192]:
r5[1:4] # upper bound excluded
# index 4 means:5th row :123

array([[157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123]])

In [193]:
r5

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [195]:
r5[:,1:4]

array([[117, 192, 198],
       [197, 104, 145],
       [ 80,  97, 162],
       [101, 120, 157],
       [118, 142, 161]])

In [196]:
r5[::]

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [197]:
r5[:]

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [201]:
r5[::-1]# reversing the order of array

array([[106, 118, 142, 161, 190],
       [162, 101, 120, 157, 123],
       [166,  80,  97, 162,  77],
       [157, 197, 104, 145, 192],
       [100, 117, 192, 198, 110]])

In [202]:
r5[::-2]

array([[106, 118, 142, 161, 190],
       [166,  80,  97, 162,  77],
       [100, 117, 192, 198, 110]])

In [203]:
r5

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [204]:
r5[::2] # alternate rows

array([[100, 117, 192, 198, 110],
       [166,  80,  97, 162,  77],
       [106, 118, 142, 161, 190]])

In [205]:
r5[::2,::2] # alternate col values in alternate rows

array([[100, 192, 110],
       [166,  97,  77],
       [106, 142, 190]])

In [206]:
r5

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [210]:
r5>200 # boolean array

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [212]:
r5[r5>100]

array([117, 192, 198, 110, 157, 197, 104, 145, 192, 166, 162, 162, 101,
       120, 157, 123, 106, 118, 142, 161, 190])

In [216]:
new=r5[r5>100]
new.reshape(3,7)

array([[117, 192, 198, 110, 157, 197, 104],
       [145, 192, 166, 162, 162, 101, 120],
       [157, 123, 106, 118, 142, 161, 190]])

#### Computation

In [217]:
# create one formal matrix of size 5x5
# perform all the arithmetic operations

In [219]:
manual=n.arange(200,500,12).reshape(5,5)
manual

array([[200, 212, 224, 236, 248],
       [260, 272, 284, 296, 308],
       [320, 332, 344, 356, 368],
       [380, 392, 404, 416, 428],
       [440, 452, 464, 476, 488]])

In [220]:
r5

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [221]:
print(r5+manual)

[[300 329 416 434 358]
 [417 469 388 441 500]
 [486 412 441 518 445]
 [542 493 524 573 551]
 [546 570 606 637 678]]


In [224]:
if r5.all()>manual.all():
    print(r5-manual)

In [231]:
for i,j in zip(r5,manual):
    for col,cl in zip(i,j):
        print(col,cl)
    print()

100 200
117 212
192 224
198 236
110 248

157 260
197 272
104 284
145 296
192 308

166 320
80 332
97 344
162 356
77 368

162 380
101 392
120 404
157 416
123 428

106 440
118 452
142 464
161 476
190 488



In [264]:
def greater(a,b):
    if a>b:
        return a
    else:return b
#greater(r5.all(),manual.all())

True

In [265]:
greater(5,8)

8

In [266]:
greater(10,3)

10

In [267]:
greater([5,6,12],[3,7,10])

[5, 6, 12]

In [269]:
greater((9,4,5),(12,1,3))

(12, 1, 3)

In [263]:
x=r5.all()
y=manual.any()
print(x,y)

True True


In [229]:
for ele in r5:
    print(ele,end=" ")

[100 117 192 198 110] [157 197 104 145 192] [166  80  97 162  77] [162 101 120 157 123] [106 118 142 161 190] 

In [232]:
r5*manual

array([[20000, 24804, 43008, 46728, 27280],
       [40820, 53584, 29536, 42920, 59136],
       [53120, 26560, 33368, 57672, 28336],
       [61560, 39592, 48480, 65312, 52644],
       [46640, 53336, 65888, 76636, 92720]])

In [234]:
r5/manual

array([[0.5       , 0.55188679, 0.85714286, 0.83898305, 0.44354839],
       [0.60384615, 0.72426471, 0.36619718, 0.48986486, 0.62337662],
       [0.51875   , 0.24096386, 0.28197674, 0.45505618, 0.20923913],
       [0.42631579, 0.25765306, 0.2970297 , 0.37740385, 0.28738318],
       [0.24090909, 0.26106195, 0.30603448, 0.33823529, 0.38934426]])

In [235]:
r5//manual

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [239]:
rem=r5%manual
rem

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]], dtype=int32)

In [237]:
r5+10 # adding num 10 to array:braoad casting

array([[110, 127, 202, 208, 120],
       [167, 207, 114, 155, 202],
       [176,  90, 107, 172,  87],
       [172, 111, 130, 167, 133],
       [116, 128, 152, 171, 200]])

In [240]:
n.min(rem)

77

In [241]:
n.max(rem)

198

In [242]:
n.mean(rem)

138.96

In [243]:
n.sum(rem)

3474

In [244]:
sum(rem) # summation of each row

array([691, 613, 655, 823, 692], dtype=int32)

#### Scientific Computation
- logarithms and exponentials

In [245]:
n.log(1)

0.0

In [246]:
n.log(10)

2.302585092994046

In [247]:
n.log2(2)

1.0

In [248]:
n.exp(1)

2.718281828459045

In [249]:
n.exp(2)

7.38905609893065

In [250]:
n.exp(n.log(1)) # finding the exponential of log1

1.0

In [251]:
n.log(n.exp(1))

1.0

In [252]:
n.exp(1)

2.718281828459045

In [253]:
n.sin(60)

-0.3048106211022167

In [254]:
n.sin(90)

0.8939966636005579

In [255]:
n.sin(180)

-0.8011526357338304

In [256]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [257]:
n.sin(0)

0.0

In [258]:
n.cos(90)

-0.4480736161291701

##### Vectorized functions
- it will consider both magnitude and direction(dimension)

In [270]:
g=n.vectorize(greater)
g(r5,manual)

array([[200, 212, 224, 236, 248],
       [260, 272, 284, 296, 308],
       [320, 332, 344, 356, 368],
       [380, 392, 404, 416, 428],
       [440, 452, 464, 476, 488]])

In [273]:
r5,manual

(array([[100, 117, 192, 198, 110],
        [157, 197, 104, 145, 192],
        [166,  80,  97, 162,  77],
        [162, 101, 120, 157, 123],
        [106, 118, 142, 161, 190]]), array([[200, 212, 224, 236, 248],
        [260, 272, 284, 296, 308],
        [320, 332, 344, 356, 368],
        [380, 392, 404, 416, 428],
        [440, 452, 464, 476, 488]]))

In [274]:
g([5,6,10],[10,7,3]) # list

array([10,  7, 10])

In [275]:
r5

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [276]:
manual

array([[200, 212, 224, 236, 248],
       [260, 272, 284, 296, 308],
       [320, 332, 344, 356, 368],
       [380, 392, 404, 416, 428],
       [440, 452, 464, 476, 488]])

In [277]:
rn=n.random.randint(50,300,25).reshape(5,5)
rn

array([[250,  78, 167, 212, 248],
       [153, 218, 218, 116, 284],
       [183,  60, 161, 204, 297],
       [202,  74, 272, 262, 271],
       [119, 120, 118, 265, 210]])

In [278]:
r5

array([[100, 117, 192, 198, 110],
       [157, 197, 104, 145, 192],
       [166,  80,  97, 162,  77],
       [162, 101, 120, 157, 123],
       [106, 118, 142, 161, 190]])

In [279]:
g(r5,rn)

array([[250, 117, 192, 212, 248],
       [157, 218, 218, 145, 284],
       [183,  80, 161, 204, 297],
       [202, 101, 272, 262, 271],
       [119, 120, 142, 265, 210]])

In [280]:
import math

In [281]:
import random

In [282]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [284]:
dir(random)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_BuiltinMethodType',
 '_MethodType',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_inst',
 '_itertools',
 '_log',
 '_os',
 '_pi',
 '_random',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']